spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    version: 1

---
spring:
  config:
    activate:
      on-profile: local
    import: application-local.yml

---
spring:
  config:
    activate:
      on-profile: ci
    import: application-ci.yml

---
spring:
  config:
    activate:
      on-profile: dev
    import:
      - classpath:yml-config/application-dev.yml
