spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mysql:8.0:///lottery_testcontainers
    username: root
    password: password
  jpa:
    hibernate:
      format_sql: true
      show_sql: true

chatgpt:
  api-key: key
  prompt: "prompt"
