name: lottery deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: 타임존 설정
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Seoul"

      - name: 저장소 Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTION_TOKEN }}

      - name: update submodules
        run: git submodule update --remote

      - name: 스프링부트 애플리케이션 빌드
        run: ./gradlew bootJar

      - name: 도커 이미지 빌드
        run: sudo docker build -f ./docker/Dockerfile-dev -t ${{ secrets.BIRCA_DEV_IMAGE }} .

      - name: 도커 이미지 push
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker push ${{ secrets.BIRCA_DEV_IMAGE }} 

      - name: scp docker-compose-dev file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "./src/main/resources/yml-config/docker/docker-compose-dev.yml"
          target: "/home/ubuntu"
          strip_components: 6

      - name: 배포
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            sudo docker stop $(sudo docker ps -a -q) 
            sudo docker rm -f $(sudo docker ps -qa)
            sudo docker pull ${{ secrets.BIRCA_DEV_IMAGE }}
            sudo docker-compose -f docker-compose-dev.yml up -d
            sudo docker image prune -f
            sudo docker volume prune -f
